-- 1. Tạo bảng dang_ky
CREATE TABLE IF NOT EXISTS public.dang_ky (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- STT tự tăng
  full_name TEXT NOT NULL,                                -- Họ và tên
  birth_date DATE NOT NULL,                               -- Ngày sinh
  rank_position TEXT NOT NULL,                            -- Cấp bậc, chức vụ
  unit TEXT NOT NULL,                                     -- Đơn vị
  phone TEXT NOT NULL,                                    -- Số điện thoại
  email TEXT NOT NULL,                                    -- Email
  notes TEXT,                                             -- Ghi chú
  created_at TIMESTAMPTZ DEFAULT NOW()                   -- Thời gian đăng ký
);

-- 2. Bật Row Level Security (RLS)
ALTER TABLE public.dang_ky ENABLE ROW LEVEL SECURITY;

-- 3. Tạo Policy cho phép MỌI NGƯỜI (Public) có thể gửi đăng ký (INSERT)
CREATE POLICY "Cho phép mọi người gửi đăng ký" 
ON public.dang_ky 
FOR INSERT 
WITH CHECK (true);

-- 4. Tạo Policy cho phép MỌI NGƯỜI (Public/Anon) có quyền xem dữ liệu (SELECT)
-- Để Admin Dashboard trên webapp có thể hiển thị dữ liệu
CREATE POLICY "Cho phép mọi người xem danh sách" 
ON public.dang_ky 
FOR SELECT 
USING (true);

-- 5. Cấp quyền truy cập cho role anon (Public API)
GRANT SELECT, INSERT ON public.dang_ky TO anon;
GRANT SELECT, INSERT ON public.dang_ky TO authenticated;
GRANT ALL ON public.dang_ky TO service_role;
