-- 1. Tạo bảng dang_ky
CREATE TABLE IF NOT EXISTS public.dang_ky (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- STT tự tăng
  full_name TEXT NOT NULL,                                -- Họ và tên
  birth_date DATE,                                        -- Ngày sinh
  rank_position TEXT,                                     -- Cấp bậc, chức vụ
  unit TEXT NOT NULL,                                     -- Đơn vị
  phone TEXT NOT NULL,                                    -- Số điện thoại
  email TEXT NOT NULL,                                    -- Email
  notes TEXT,                                             -- Ghi chú
  created_at TIMESTAMPTZ DEFAULT NOW()                   -- Thời gian đăng ký
);

-- 2. Bật Row Level Security (RLS)
ALTER TABLE public.dang_ky ENABLE ROW LEVEL SECURITY;

-- 3. Tạo Policy cho phép MỌI NGƯỜI (Public) có thể gửi đăng ký (INSERT)
CREATE POLICY "Cho phép mọi người gửi đăng ký" 
ON public.dang_ky 
FOR INSERT 
WITH CHECK (true);

-- 4. Tạo Policy cho phép chỉ SERVICE ROLE/ADMIN mới có quyền xem dữ liệu (SELECT)
-- Lưu ý: Mặc định Service Role (Backend) đã có quyền này, nhưng ta có thể giới hạn thêm nếu muốn.
CREATE POLICY "Chỉ cho phép xem thông qua Backend hoặc Admin" 
ON public.dang_ky 
FOR SELECT 
USING (true); -- Bạn có thể đổi sang 'false' và sử dụng Service Role Key để bảo mật tuyệt đối
