-- Tạo bảng lưu kết quả bài kiểm tra cuối khóa
CREATE TABLE IF NOT EXISTS public.kq_test (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name TEXT NOT NULL,
  rank_position TEXT NOT NULL,
  unit TEXT NOT NULL,
  quiz_id TEXT,
  quiz_title TEXT,
  total_questions INTEGER NOT NULL DEFAULT 30,
  score INTEGER NOT NULL DEFAULT 0,
  max_score INTEGER NOT NULL DEFAULT 30,
  percentage NUMERIC(5,2) NOT NULL DEFAULT 0,
  questions JSONB NOT NULL DEFAULT '[]'::jsonb,
  answers JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.kq_test ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Cho phép mọi người gửi bài kiểm tra"
ON public.kq_test
FOR INSERT
WITH CHECK (true);

CREATE POLICY "Cho phép mọi người xem kết quả kiểm tra"
ON public.kq_test
FOR SELECT
USING (true);

GRANT SELECT, INSERT ON public.kq_test TO anon;
GRANT SELECT, INSERT ON public.kq_test TO authenticated;
GRANT ALL ON public.kq_test TO service_role;

-- Bảng cấu hình ứng dụng, dùng để đóng/mở bài kiểm tra
CREATE TABLE IF NOT EXISTS public.app_settings (
  key TEXT PRIMARY KEY,
  value JSONB NOT NULL DEFAULT '{}'::jsonb,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.app_settings ENABLE ROW LEVEL SECURITY;

INSERT INTO public.app_settings (key, value)
VALUES ('test_open', '{"open": true}'::jsonb)
ON CONFLICT (key) DO NOTHING;

DROP POLICY IF EXISTS "Cho phép mọi người xem cấu hình" ON public.app_settings;
CREATE POLICY "Cho phép mọi người xem cấu hình"
ON public.app_settings
FOR SELECT
USING (true);

DROP POLICY IF EXISTS "Cho phép cập nhật cấu hình" ON public.app_settings;
CREATE POLICY "Cho phép cập nhật cấu hình"
ON public.app_settings
FOR ALL
USING (true)
WITH CHECK (true);

GRANT SELECT, INSERT, UPDATE ON public.app_settings TO anon;
GRANT SELECT, INSERT, UPDATE ON public.app_settings TO authenticated;
GRANT ALL ON public.app_settings TO service_role;
