-- Bang luu ket qua bai kiem tra cuoi khoa
CREATE TABLE IF NOT EXISTS public.kq_test (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name TEXT NOT NULL,
  rank_position TEXT NOT NULL,
  unit TEXT NOT NULL,
  quiz_id TEXT,
  quiz_title TEXT,
  total_questions INTEGER NOT NULL DEFAULT 30,
  score INTEGER NOT NULL DEFAULT 0,
  max_score INTEGER NOT NULL DEFAULT 30,
  percentage NUMERIC(5,2) NOT NULL DEFAULT 0,
  questions JSONB NOT NULL DEFAULT '[]'::jsonb,
  answers JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.kq_test ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Cho phep moi nguoi gui bai kiem tra" ON public.kq_test;
CREATE POLICY "Cho phep moi nguoi gui bai kiem tra"
ON public.kq_test
FOR INSERT
WITH CHECK (true);

DROP POLICY IF EXISTS "Cho phep moi nguoi xem ket qua kiem tra" ON public.kq_test;
CREATE POLICY "Cho phep moi nguoi xem ket qua kiem tra"
ON public.kq_test
FOR SELECT
USING (true);

GRANT SELECT, INSERT ON public.kq_test TO anon;
GRANT SELECT, INSERT ON public.kq_test TO authenticated;
GRANT ALL ON public.kq_test TO service_role;

-- Bang cau hinh ung dung, dung de dong/mo bai kiem tra
CREATE TABLE IF NOT EXISTS public.app_settings (
  key TEXT PRIMARY KEY,
  value JSONB NOT NULL DEFAULT '{}'::jsonb,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.app_settings ENABLE ROW LEVEL SECURITY;

INSERT INTO public.app_settings (key, value)
VALUES ('test_open', '{"open": true}'::jsonb)
ON CONFLICT (key) DO NOTHING;

DROP POLICY IF EXISTS "Cho phep moi nguoi xem cau hinh" ON public.app_settings;
CREATE POLICY "Cho phep moi nguoi xem cau hinh"
ON public.app_settings
FOR SELECT
USING (true);

DROP POLICY IF EXISTS "Cho phep cap nhat cau hinh" ON public.app_settings;
CREATE POLICY "Cho phep cap nhat cau hinh"
ON public.app_settings
FOR ALL
USING (true)
WITH CHECK (true);

GRANT SELECT, INSERT, UPDATE ON public.app_settings TO anon;
GRANT SELECT, INSERT, UPDATE ON public.app_settings TO authenticated;
GRANT ALL ON public.app_settings TO service_role;
